### ISSUE TITLE
Compatibility with chef 14

### ISSUE THREAD

**Issue by daften** [chef-cookbooks/php#217]
### Cookbook version
3.0.0

### Chef-client version
1
4.0.3
### Platform Details
Docker container on travis through kitchen-dokken

### Scenario:
Run a wrapper cookbook on chef 14

### Steps to Reproduce:
I noticed this by accident while setting up travis and kitchen-dokken. This kitchen.dokken file did it for me:
```
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: current

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: false

platforms:
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools
```

### Expected Result:
The cookbook to run.

### Actual Result:
A recipe compile error.

```
================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/php/providers/pear.rb
================================================================================
LoadError
---------
cannot load such file -- chef/mixin/language
Cookbook Trace:
---------------
  /opt/kitchen/cache/cookbooks/php/providers/pear.rb:24:in `class_from_file'
Relevant File Content:
----------------------
/opt/kitchen/cache/cookbooks/php/providers/pear.rb:
 17:  # See the License for the specific language governing permissions and
 18:  # limitations under the License.
 19:  #
 20:  
 21:  use_inline_resources
 22:  
 23:  require 'chef/mixin/shell_out'
 24>> require 'chef/mixin/language'
 25:  include Chef::Mixin::ShellOut
 26:  
 27:  # the logic in all action methods mirror that of
 28:  # the Chef::Provider::Package which will make
 29:  # refactoring into core chef easy
 30:  
 31:  use_inline_resources
 32:  
 33:  def whyrun_supported?
System Info:
------------
chef_version=14.0.3
platform=centos
platform_version=7.4.1708
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=chef-client worker: ppid=67;start=12:48:46;
executable=/opt/chef/embedded/bin/chef-client
```
